# Generated by Django 3.1.2 on 2020-12-11 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='watch_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='watchlistusers', to=settings.AUTH_USER_MODEL),
        ),
    ]
