# Generated by Django 3.1.2 on 2020-12-11 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_watchlist_watch_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='watch_user',
        ),
    ]
