# Generated by Django 3.1.2 on 2020-12-12 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_watchlist_watch_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='description',
            field=models.CharField(default='', max_length=15),
        ),
    ]
