# Generated by Django 3.1.2 on 2020-12-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20201212_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='category',
            field=models.CharField(choices=[('FOT', 'Footwear'), ('CLO', 'Clothes'), ('INT', 'Instruments'), ('ELE', 'Electronics'), ('OTH', 'Other')], default='', max_length=10),
        ),
    ]
